TOKEN = '6701143845:AAEHe8THtYJDnOhR378PkoT9io8tzXLoi3Y'

MYSQL_USER = 'root'
MYSQL_PASSWORD = 'qwerty123'
MYSQL_DATABASE = 'shop_db'
MYSQL_HOST = 'localhost'





MYSQL_URL = f'mysql+aiomysql://{MYSQL_USER}:{MYSQL_PASSWORD}@{MYSQL_HOST}/{MYSQL_DATABASE}'